services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-api
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
